[project]
name = "vdiup-argo"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "cartopy",
    "cmocean",
    "earthaccess",
    "geopandas",
    "kaleido",
    "matplotlib",
    "netCDF4",
    "numpy",
    "pandas",
    "plotly",
    "pysolar",
    "scipy",
    "statsmodels",
    "xarray",
]

[project.optional-dependencies]
obsolete = [
    "pvlib",
    "seawater",
]
